### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by dandv** [eruizdechavez/mdwiki#15]
Good to see a wiki developed in Node, but sad to see it's no longer maintained.

Would it make sense to join forces with one of the more popular and active projects? The top three are [Jingo](https://github.com/claudioc/jingo), [openKB](https://github.com/mrvautin/openKB) and [Hazel](https://github.com/wkallhof/Hazel).

Thanks!

**Comment by eruizdechavez** [comment]
Thanks for the comment @dandv. 

This project was never intended to be a full fledged Wiki. The idea behind it was to provide with a quick way to start a local server for browsing your project's documentation.

If you have a special request I'd gladly review it. Otherwise it might be a wise decision to follow your advice and join forces with current active projects.

**Comment by eruizdechavez** [comment]
@yesidiaz @parga thoughts?

I'll review the stats in npm and other available projects.
